// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrMIPbrPX0WVXrISQAKl6_J_xD2g70NVs',
    appId: '1:536858787425:web:2c70be4a660e87cbed7420',
    messagingSenderId: '536858787425',
    projectId: 'cep-eczane',
    authDomain: 'cep-eczane.firebaseapp.com',
    storageBucket: 'cep-eczane.appspot.com',
    measurementId: 'G-8E9WHB80B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdk22Y0r93o0PenMPYKdV8nQJPHsLRzlI',
    appId: '1:536858787425:android:8f6c5da28eb76657ed7420',
    messagingSenderId: '536858787425',
    projectId: 'cep-eczane',
    storageBucket: 'cep-eczane.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbHfVG3M2hxTt8ti8yOFoG0j6XhfvDxtk',
    appId: '1:536858787425:ios:1f7fedf639f268bced7420',
    messagingSenderId: '536858787425',
    projectId: 'cep-eczane',
    storageBucket: 'cep-eczane.appspot.com',
    iosBundleId: 'com.example.cepEczane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbHfVG3M2hxTt8ti8yOFoG0j6XhfvDxtk',
    appId: '1:536858787425:ios:1f7fedf639f268bced7420',
    messagingSenderId: '536858787425',
    projectId: 'cep-eczane',
    storageBucket: 'cep-eczane.appspot.com',
    iosBundleId: 'com.example.cepEczane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrMIPbrPX0WVXrISQAKl6_J_xD2g70NVs',
    appId: '1:536858787425:web:cb16fb3694c7fd5ded7420',
    messagingSenderId: '536858787425',
    projectId: 'cep-eczane',
    authDomain: 'cep-eczane.firebaseapp.com',
    storageBucket: 'cep-eczane.appspot.com',
    measurementId: 'G-VPY4F68CG4',
  );
}
